name: ""

services:
  frontend:
    build: "./frontend"
    depends_on:
      - backend
    restart: always
  backend:
    build: "./backend"
    depends_on:
      - database
    restart: always
  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
  nginx:
    image: "nginx:alpine"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
